# Generated by Django 3.0.4 on 2020-06-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
