# Generated by Django 3.0.4 on 2020-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200613_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='damage_cost_tomans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
