# Generated by Django 3.0.4 on 2020-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200614_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='damage_cost_tomans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
